global proc randPlaceGen(int $duplicates, float $xMin, float $xMax, float $yMin, float $yMax, float $zMin, float $zMax){
    string $selObjs[] = `ls -sl`;
    string $dupes[];
    for( $i= 0; $i < $duplicates; $i++){
        $dupes = `duplicate $selObjs`;
        for($j in $dupes){
            move (`rand $xMin $xMax`) (`rand $yMin $yMax`)(`rand $zMin $zMax`) $j;
        }
    }
}

randPlaceGen(20, -10, 10, 0 ,0 , -10, 10);